### PR TITLE
[18149] Fix build on msvc 19.36.32528

### LINKED ISSUE #3451: [18147] xtime will be changed to _timespec64 in an upcoming release of MSVC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

No error.

### Current behavior

Hello, I'm a member of Microsoft [VCPKG](https://github.com/microsoft/vcpkg), when I built this port in an internal version of MSVC, it failed with following errors:
```
D:\buildtrees\fastrtps\src\v2.7.0-5b113921c9.clean\include\fastrtps/utils/TimedMutex.hpp(93): error C2065: 'xtime': undeclared identifier
D:\buildtrees\fastrtps\src\v2.7.0-5b113921c9.clean\include\fastrtps/utils/TimedMutex.hpp(93): error C2059: syntax error: ')'
```

### Steps to reproduce

Build with MSVC `19.36.32528.95` and above, `xtime` has been changed to `_timespec64` since https://github.com/microsoft/STL/pull/3594, it's an upcoming release.

### Fast DDS version/commit

`2.7.0`. For details, see: [fastrtps/vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/ports/fastrtps/vcpkg.json)

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

* Windows
* Visual Studio

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This should fix #3451 by adding an alias for `xtime` on newer versions of MSVC.

@Mergifyio backport 2.9.x 2.6.x 2.1.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by JesusPoderoso** [comment]
@Mergifyio backport 2.9.x 2.6.x 2.1.x

**Review by JesusPoderoso — APPROVED** [review]
LGTM
