### PR TITLE
[24101] Fix build in GCC 15

### LINKED ISSUE #6254: Missing cstdint include
### Is there an already existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

Expected: compilation works with GCC 15.2.0.

### Current behavior

Compilation with GCC 15.2.0 of Fast-DDS v3.4.1 fails due to missing `#include <cstdint>` in SharedSecretHandle.h.

https://github.com/eProsima/Fast-DDS/blob/3e3f2619a6615c583bccb7d81ab8a5a89138257a/src/cpp/rtps/security/common/SharedSecretHandle.h

```
[ 89%] Building CXX object src/cpp/CMakeFiles/fastdds.dir/rtps/security/common/SharedSecretHandle.cpp.o
In file included from /build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:19:
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:58:35: error: 'uint8_t' was not declared in this scope
   58 |                 const std::vector<uint8_t>& value)
      |                                   ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:24:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   23 | #include <vector>
  +++ |+#include <cstdint>
   24 | 
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:58:42: error: template argument 1 is invalid
   58 |                 const std::vector<uint8_t>& value)
      |                                          ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:58:42: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:29: error: 'uint8_t' was not declared in this scope
   66 |                 std::vector<uint8_t>&& value)
      |                             ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:29: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:36: error: template argument 1 is invalid
   66 |                 std::vector<uint8_t>&& value)
      |                                    ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:36: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:35: error: 'uint8_t' was not declared in this scope
  111 |                 const std::vector<uint8_t>& value)
      |                                   ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:35: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:42: error: template argument 1 is invalid
  111 |                 const std::vector<uint8_t>& value)
      |                                          ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:42: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:29: error: 'uint8_t' was not declared in this scope
  117 |                 std::vector<uint8_t>&& value)
      |                             ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:29: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:36: error: template argument 1 is invalid
  117 |                 std::vector<uint8_t>&& value)
      |                                    ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:36: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:27: error: 'uint8_t' was not declared in this scope
  122 |         const std::vector<uint8_t>& value() const
      |                           ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:27: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:34: error: template argument 1 is invalid
  122 |         const std::vector<uint8_t>& value() const
      |                                  ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:34: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:21: error: 'uint8_t' was not declared in this scope
  127 |         std::vector<uint8_t>& value()
      |                     ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:21: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:28: error: template argument 1 is invalid
  127 |         std::vector<uint8_t>& value()
      |                            ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:28: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:21: error: 'uint8_t' was not declared in this scope
  136 |         std::vector<uint8_t> value_;
      |                     ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:21: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:28: error: template argument 1 is invalid
  136 |         std::vector<uint8_t> value_;
      |                            ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:28: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:30: error: 'uint8_t' was not declared in this scope
  152 |     static const std::vector<uint8_t>* find_data_value(
      |                              ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:30: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:37: error: template argument 1 is invalid
  152 |     static const std::vector<uint8_t>* find_data_value(
      |                                     ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:37: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:25:19: error: 'uint8_t' was not declared in this scope
   25 | const std::vector<uint8_t>* SharedSecretHelper::find_data_value(
      |                   ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:20:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   19 | #include <rtps/security/common/SharedSecretHandle.h>
  +++ |+#include <cstdint>
   20 | 
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:25:26: error: template argument 1 is invalid
   25 | const std::vector<uint8_t>* SharedSecretHelper::find_data_value(
      |                          ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:25:26: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp: In static member function 'static const int* eprosima::fastdds::rtps::security::SharedSecretHelper::find_data_value(const eprosima::fastdds::rtps::security::SecretHandle&, const std::string&)':
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:23: error: 'uint8_t' was not declared in this scope
   29 |     const std::vector<uint8_t>* returnedValue = nullptr;
      |                       ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:23: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:30: error: template argument 1 is invalid
   29 |     const std::vector<uint8_t>* returnedValue = nullptr;
      |                              ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:30: error: template argument 2 is invalid
make[2]: *** [src/cpp/CMakeFiles/fastdds.dir/build.make:3369: src/cpp/CMakeFiles/fastdds.dir/rtps/security/common/SharedSecretHandle.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:398: src/cpp/CMakeFiles/fastdds.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### Steps to reproduce

Build with new GCC.

### Fast DDS version/commit

3e3f2619a6615c583bccb7d81ab8a5a89138257a

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

_No response_

### XML configuration file

```xml

```

### Relevant log output

```shell

```

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by raulojeda22**
## Description
Fix compilation with GCC 15 by adding missing `#include <cstdint>` to `SharedSecretHandle.h`.
GCC 15 is stricter about implicit includes, and `uint8_t` requires an explicit `#include <cstdint>`. Without this include, compilation fails with errors like:
```
error: 'uint8_t' was not declared in this scope
```

Additionally, GCC 15 shows a false positive warning in sqlite3.c:
```
warning: ‘strlen’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
35253 |   return 0x3fffffff & (int)strlen(z);
```

Which is fixed in this PR by changing the if statement to a ternary operator.

@Mergifyio backport 3.4.x 3.3.x 3.2.x 2.14.x

Fixes #6254

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- _N/A_: If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

File: .github/workflows/docker/ubuntu/alternative_builds/fastdds_gcc_latest.Dockerfile [hunk 1]
```diff
@@ -47,4 +47,4 @@ RUN apt-get update && apt-get install --yes --no-install-recommends \
     libtinyxml2-dev \
     openssl
 
-ENTRYPOINT ["/bin/bash", "-c", "cd && colcon build --event-handlers=console_direct+"]
+ENTRYPOINT ["/bin/bash", "-c", "cd && colcon build --event-handlers=console_direct+ -DSECURITY=ON -DFASTDDS_STATISTICS=ON"]
```
Comment (cferreiragonz) [inline .github/workflows/docker/ubuntu/alternative_builds/fastdds_gcc_latest.Dockerfile]: We are missing `--cmake-args` before the new flags

File: src/cpp/rtps/security/common/SharedSecretHandle.h [hunk 2]
```diff
@@ -21,6 +21,7 @@
 #include <rtps/security/common/Handle.h>
 
 #include <vector>
+#include <cstdint>
```
Comment (cferreiragonz) [inline src/cpp/rtps/security/common/SharedSecretHandle.h:23]: Add this before the `<vector>` include to use alphabetical order

**Comment by cferreiragonz** [comment]
@Mergifyio backport 3.4.x 3.3.x 3.2.x 2.14.x
