### ISSUE TITLE
Compile error at ubuntu20.04

### ISSUE THREAD

**Issue by p-zzg** [eProsima/Fast-DDS#5781]
### Is there an already existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

[100%] Linking CXX shared library libfastrtps.so
[100%] Built target fastrtps
[100%] Building CXX object tools/fds/CMakeFiles/fast-discovery-server.dir/server.cpp.o
[100%] Linking CXX executable fast-discovery-server-1.0.1
/usr/bin/ld: ../../src/cpp/libfastrtps.so.2.14.4: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/fds/CMakeFiles/fast-discovery-server.dir/build.make:104: tools/fds/fast-discovery-server-1.0.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:967: tools/fds/CMakeFiles/fast-discovery-server.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

In ubuntu20.04 supports gcc9 by default, but this one needs gcc11, only this small bug, I hope there is a temporary solution, thanks

### Current behavior

Compile error at ubuntu20.04

### Steps to reproduce

Compile fine in ubuntu20.04

### Fast DDS version/commit

fastdds 2.14.x

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

### XML configuration file

```xml

```

### Relevant log output

```shell

```
