### ISSUE TITLE
[GCC15] Build error due to unused using declaration

### ISSUE THREAD

**Issue by oysstu** [eProsima/Fast-DDS#5792]
### Is there an already existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

Build success. Removing the line below solves the issue.
https://github.com/eProsima/Fast-DDS/blob/4e8c57227ab3d6aa0041cf6316521fbd59bfe38b/src/cpp/rtps/reader/BaseReader.cpp#L520

### Current behavior

Build fail

### Steps to reproduce

Build with GCC (15.1.1)

### Fast DDS version/commit

master

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

ROS2 Kilted beta

### XML configuration file

```xml

```

### Relevant log output

```shell
Fast-DDS/src/cpp/rtps/reader/BaseReader.cpp: In member function ‘void eprosima::fastdds::rtps::BaseReader::setup_datasharing(const eprosima::fastdds::rtps::ReaderAttributes&)’:
Fast-DDS/src/cpp/rtps/reader/BaseReader.cpp:520:34: error: unused using-declaration ‘std::placeholders::_1’ [-Werror=unused-variable]
  520 |         using std::placeholders::_1;
      |                                  ^~
cc1plus: all warnings being treated as errors
```
