### ISSUE TITLE
Including FastRTPS in Qt Projects: LNK2005 already defined [8982]

### ISSUE THREAD

**Issue by jenskarch** [eProsima/Fast-DDS#904]
When trying to include FastRTPS to my Qt Project using qmake like that:

```
win32: LIBS += -L$$PWD/../../../../_programme/FastRTPSv1.9/lib/x64Win64VS2017/ -lfastrtps-1.9

INCLUDEPATH += $$PWD/../../../../_programme/FastRTPSv1.9/include
DEPENDPATH += $$PWD/../../../../_programme/FastRTPSv1.9/include

win32:!win32-g++: PRE_TARGETDEPS += $$PWD/../../../../_programme/FastRTPSv1.9/lib/x64Win64VS2017/fastrtps-1.9.lib
else:win32-g++: PRE_TARGETDEPS += $$PWD/../../../../_programme/FastRTPSv1.9/lib/x64Win64VS2017/libfastrtps-1.9.a
```

Errors like the following occur:

`libfastrtps-1.9.lib(TypeIdentifier.obj):-1: Fehler: LNK2005: "public: __cdecl eprosima::fastrtps::types::TypeIdentifier::TypeIdentifier(void)" (??0TypeIdentifier@types@fastrtps@eprosima@@QEAA@XZ) ist bereits in fastrtps-1.9.lib(fastrtps-1.9.dll) definiert.`

libfastrtps-1.9.lib says everything was already defined in fastrtps-1.9.lib

**Comment by richiware** [comment]
Fast-RTPS uses a mechanism to autolink libraries using `#pragma`, similar to Boost libraries mechanism. You can deactivate it using the define `-DFASTRTPS_NO_LIB`.

**Comment by jenskarch** [comment]
> Fast-RTPS uses a mechanism to autolink libraries using `#pragma`, similar to Boost libraries mechanism. You can deactivate it using the define `-DFASTRTPS_NO_LIB`.

Thank you for the reply, that's probably the reason. Where do I use that define? Do I have to build fastrtps from source and pass that flag to colcon somehow?

**Comment by richiware** [comment]
Using `colcon`, the best way would be using a `colcon.meta` file.
```yaml
{
    "names":
    {
        "fastrtps" :
        {
            "cmake-args": ["-DCMAKE_CXX_FLAGS=/DFASTRTPS_NO_LIB"]
        }
    }
}
```
I was not able to check this `colcon.meta`. I hope it works at first time. Maybe I wrote something wrong.

About the auto-link using headers is inherited from the past, when Fast-RTPS didn't use CMake. We will study if it still necessary.

**Comment by jenskarch** [comment]
Thanks for your help. Indeed the LNK 2005 problem is gone now (btw using `colcon build --cmake-args "-DCMAKE_CXX_FLAGS=/DFASTRTPS_NO_LIB"` works too)  but I get unresolved externals on fastdds. But there is no lib to include to my project. the fastrtps/lib folder just contains "fastrtps-1.9.lib" when building with colcon.

**Comment by richiware** [comment]
Are you using Fast-RTPS `master` branch? I suppose that because you got unresolved externals on `fastdds`, and that API is only in `master` branch right now. If this is the case, please, use the stable branch `1.9.x`.

**Comment by jenskarch** [comment]
I am using this command from the github page:

`wget https://raw.githubusercontent.com/eProsima/Fast-RTPS/master/fastrtps.repos`

so yes, it looks like I am on the master branch. Once I get home, I'll try it with the other branch again

**Comment by jenskarch** [comment]
Okay the fastdds linker errrors are gone, but are replaced with fastrtps linker errors:

This is what I am left with:

![Unbenannt](https://user-images.githubusercontent.com/38098635/70257172-1b598a00-178a-11ea-8f06-72e414af0cfb.JPG)

**Comment by richiware** [comment]
How do you create the objects `PublisherAttributes` and `SubscriberAttributes` in your code? The problem your seeing was detected when their default constructor is not used. Try to create these objects with the default constructor and then fill them. E.g:

```c++
PublisherAttributes publisher_attr;
publisher_attr.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
```

**Comment by jenskarch** [comment]
This is how the publisherattributes are created (this should comply to the way the generator does it, since this should be untouched code straight from the generator):

  ```
  PublisherAttributes Wparam;
    Wparam.topic.topicKind = NO_KEY;
    Wparam.topic.topicDataType = myType.getName();  //This type MUST be registered
    Wparam.topic.topicName = "PositionTopicPubSubTopic";
```

**Comment by richiware** [comment]
VS 2015 solution generation was maintained for nostalgic reasons, but I didn't test it long ago. I recommend you to generate the CMake script, and then use CMake to generate the VS 2017 solution.

**Comment by jenskarch** [comment]
Okay to get back to the problem (which I still didn't solve) after my holidays I have two questions:

a) I am using code from the latest FastRTPS-Code-Generator. That should be valid to work with FastRTPS v1.9 x64Win64VS2017 correct?

b) I am still stuck with linker errors. Using the precompiled version from your download page it gives me the "already defined errors". That might be caused by the automatic linking, but compiling FastRTPS from source with the flag FASTRTPS_NO_LIB gives me other linker errors "unresolved external symbol". What libs do I have to link against when I use the FASTRTPS_NO_LIB flag?

**Comment by richiware** [comment]
I'll try to answer:

> a) I am using code from the latest FastRTPS-Code-Generator. That should be valid to work with FastRTPS v1.9 x64Win64VS2017 correct?

Yes, last *Fast-RTPS-Gen* source code should work with FastRTPS v1.9 x64Win64VS2017. I recommend generating the CMake project and use it to generate the VS solution.

> b) I am still stuck with linker errors. Using the precompiled version from your download page it gives me the "already defined" errors. That might be caused by the automatic linking, but compiling FastRTPS from source with the flag FASTRTPS_NO_LIB, which should solve this, gives me other linker errors "unresolved external symbol". What libs do I have to link against when I use the FASTRTPS_NO_LIB flag?

FASTRTPS_NO_LIB flag should be used in your project, and not when compiling Fast-RTPS. You can use the precompiled version but your project has to define the flag FASTRTPS_NO_LIB.

> c) I used to work with FastRTPS v1.5 and MSVC13 and everything worked fine. I had to update to MSVC17 though and now I have these problems. I also tried compiling v1.5 from source but it doesn't work anymore throwing an error "Cannot configure Git submodule fastcdr". Can someone tell me how to fix that or provide me FastRTPS 1.5 MSVC 2017 binaries?

FasRTPS 1.5 is an old version. Sorry, we cannot generate that configuration. About the error *Cannot configure Git submodule fastcdr*, Git is not finding the specific commit. *fastcdr* is a library that doesn't change in a long time. Maybe changing the submodule to point to another commit should work.

**Comment by jenskarch** [comment]
Okay I can't seem to fix the issue. I managed to add the flag to my project (I misunderstood that previously) but it still only changes the "already defined" errors to the following "unresolved external symbols":

![unresolved_ext](https://user-images.githubusercontent.com/38098635/74378299-003c7380-4de6-11ea-8aeb-bc315b920bff.JPG)

Here is how the publisher is created (I don't have a subscriber in my project):

![code](https://user-images.githubusercontent.com/38098635/74378338-10545300-4de6-11ea-984f-8d9c62f1b615.JPG)

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry @jenskarch,

Fast DDS (formerly known as FastRTPS) 1.9.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). Several changes have been introduced in newer versions of Fast DDS so this issue might be solved by upgrading the library. Also, the [official support](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platform-support) is for VS2019 (though VS2017 is considered Tier 2). I am going to close this issue. Feel free to reopen if you are still having trouble with the supported versions.
