### PR TITLE
[20413] Fix doxygen docs warnings. Prepare for compiling with Doxygen 1.10.0

### LINKED ISSUE #4370: API doc generation fails with doxygen >= 1.10.0
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Build passes, doxygen generates API doc without error.

### Current behavior

Build fails with doxygen >= 1.10.0.

The doxygen 1.10.0 [changelog](https://www.doxygen.nl/manual/changelog.html) mentions:

> Submit warning when the ingroup command is used with an non-existing group name [[view](https://github.com/doxygen/doxygen/commit/e075f1bf636ff1959dcaf0e99b9c09dc13d8008f)] and [[view](https://github.com/doxygen/doxygen/commit/9777be43fd7f2809fefcb002706977ba07c9b15c)]

and Fast-DDS's doxygen config [contains](https://github.com/eProsima/Fast-DDS/blob/v2.13.1/doxyfile.in#L839):

> WARN_AS_ERROR = YES

An inconsistency in the documentation triggers the new doxygen warning, which is being treated as error:

> `/build/source/include/fastrtps/types/AnnotationParameterValue.h:64: error: Found non-existing group 'ANNOTATIONPARAMETERVALUE' for the command '@ingroup', ignoring command (warning treated as error, aborting now)`

### Steps to reproduce

 * Get doxygen >= 1.10.0
 * Get Fast-DDS v2.13.1
 * Run cmake with `-DBUILD_DOCUMENTATION=ON`
 * Try to build FastDDS

### Fast DDS version/commit

[v2.13.1](https://github.com/eProsima/Fast-DDS/tree/v2.13.1)

https://github.com/eProsima/Fast-DDS/blob/v2.13.1/doxyfile.in#L839

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

Happens on any platform that uses doxygen >= 1.10.0.

See also https://github.com/eProsima/Fast-CDR/issues/193.

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR fixes some minor typos and declares some extra `groups` into the `doxygen_modules.h` file that fixes a compilation warning stating that the `@ingroup` doxygen macros did not point to a valid group. 

Before doxygen `1.10.0` it was not considered a warning, but, as we define `WARN_AS_ERROR` to `YES` in the `doxyfile.in`, we fail to compile with with `doxygen >= 1.10.0` since it is treated as a warning henceforth.

Two considerations:
* This PR does NOT upgrade the `doxyfile.in` to `1.10.0` yet, so building with `doxygen 1.10.0` and `-DBUILD_DOCUMENTATION=ON` outputs a bunch of info messages complaining that some of the configuration options are obsolete, but now, the compilation finishes successfully.
* Some of the fixes affect the `/types` directory which is going to be deprecated with the new XTypes refactor.

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

Fixes #4370 

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are ABI compatible. 
-**N/A** Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Review by JesusPoderoso — APPROVED** [review]
LGTM

**Comment by JesusPoderoso** [comment]
@richiprosima please test mac

**Comment by Mario-DL** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x
