### PR TITLE
Fix `-Werror=template-id-cdtor`

### LINKED ISSUE #5340: Build error because of -Werror=template-id-cdtor in C++20
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Build completes without errors.

### Current behavior

Build breaks with `thirdparty/filewatch/FileWatch.hpp:129:22: error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]`.

### Steps to reproduce

Build with gcc (GCC) 14.2.1 20240910.

### Fast DDS version/commit

3.1.0 and later for sure.

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

_No response_

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by kistlin**
## Description

solves error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]

@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x

Fixes #5340

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- **N/A** If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JesusPoderoso** [comment]
Hi @kistlin, thanks for your contribution!

**Review by Mario-DL — APPROVED** [review]
LGTM

**Comment by MiguelCompany** [comment]
@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x
