### ISSUE TITLE
Missing cstdint include

### ISSUE THREAD

**Issue by panicgh** [eProsima/Fast-DDS#6254]
### Is there an already existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

Expected: compilation works with GCC 15.2.0.

### Current behavior

Compilation with GCC 15.2.0 of Fast-DDS v3.4.1 fails due to missing `#include <cstdint>` in SharedSecretHandle.h.

https://github.com/eProsima/Fast-DDS/blob/3e3f2619a6615c583bccb7d81ab8a5a89138257a/src/cpp/rtps/security/common/SharedSecretHandle.h

```
[ 89%] Building CXX object src/cpp/CMakeFiles/fastdds.dir/rtps/security/common/SharedSecretHandle.cpp.o
In file included from /build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:19:
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:58:35: error: 'uint8_t' was not declared in this scope
   58 |                 const std::vector<uint8_t>& value)
      |                                   ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:24:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   23 | #include <vector>
  +++ |+#include <cstdint>
   24 | 
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:58:42: error: template argument 1 is invalid
   58 |                 const std::vector<uint8_t>& value)
      |                                          ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:58:42: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:29: error: 'uint8_t' was not declared in this scope
   66 |                 std::vector<uint8_t>&& value)
      |                             ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:29: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:36: error: template argument 1 is invalid
   66 |                 std::vector<uint8_t>&& value)
      |                                    ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:66:36: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:35: error: 'uint8_t' was not declared in this scope
  111 |                 const std::vector<uint8_t>& value)
      |                                   ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:35: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:42: error: template argument 1 is invalid
  111 |                 const std::vector<uint8_t>& value)
      |                                          ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:111:42: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:29: error: 'uint8_t' was not declared in this scope
  117 |                 std::vector<uint8_t>&& value)
      |                             ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:29: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:36: error: template argument 1 is invalid
  117 |                 std::vector<uint8_t>&& value)
      |                                    ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:117:36: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:27: error: 'uint8_t' was not declared in this scope
  122 |         const std::vector<uint8_t>& value() const
      |                           ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:27: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:34: error: template argument 1 is invalid
  122 |         const std::vector<uint8_t>& value() const
      |                                  ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:122:34: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:21: error: 'uint8_t' was not declared in this scope
  127 |         std::vector<uint8_t>& value()
      |                     ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:21: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:28: error: template argument 1 is invalid
  127 |         std::vector<uint8_t>& value()
      |                            ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:127:28: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:21: error: 'uint8_t' was not declared in this scope
  136 |         std::vector<uint8_t> value_;
      |                     ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:21: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:28: error: template argument 1 is invalid
  136 |         std::vector<uint8_t> value_;
      |                            ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:136:28: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:30: error: 'uint8_t' was not declared in this scope
  152 |     static const std::vector<uint8_t>* find_data_value(
      |                              ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:30: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:37: error: template argument 1 is invalid
  152 |     static const std::vector<uint8_t>* find_data_value(
      |                                     ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.h:152:37: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:25:19: error: 'uint8_t' was not declared in this scope
   25 | const std::vector<uint8_t>* SharedSecretHelper::find_data_value(
      |                   ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:20:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   19 | #include <rtps/security/common/SharedSecretHandle.h>
  +++ |+#include <cstdint>
   20 | 
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:25:26: error: template argument 1 is invalid
   25 | const std::vector<uint8_t>* SharedSecretHelper::find_data_value(
      |                          ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:25:26: error: template argument 2 is invalid
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp: In static member function 'static const int* eprosima::fastdds::rtps::security::SharedSecretHelper::find_data_value(const eprosima::fastdds::rtps::security::SecretHandle&, const std::string&)':
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:23: error: 'uint8_t' was not declared in this scope
   29 |     const std::vector<uint8_t>* returnedValue = nullptr;
      |                       ^~~~~~~
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:23: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:30: error: template argument 1 is invalid
   29 |     const std::vector<uint8_t>* returnedValue = nullptr;
      |                              ^
/build/source/src/cpp/rtps/security/common/SharedSecretHandle.cpp:29:30: error: template argument 2 is invalid
make[2]: *** [src/cpp/CMakeFiles/fastdds.dir/build.make:3369: src/cpp/CMakeFiles/fastdds.dir/rtps/security/common/SharedSecretHandle.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:398: src/cpp/CMakeFiles/fastdds.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### Steps to reproduce

Build with new GCC.

### Fast DDS version/commit

3e3f2619a6615c583bccb7d81ab8a5a89138257a

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### XML configuration file

```xml

```

### Relevant log output

```shell

```

**Comment by cferreiragonz** [comment]
Hi @panicgh, the issue should have been solved with the latest commit (8b28dabf3768ed869edeec591a0efcb2b1a897f8) of `master`. The fix will also be available in currently supported branches in future releases. Thanks for your contribution!
