### ISSUE TITLE
[18147] xtime will be changed to _timespec64 in an upcoming release of MSVC

### ISSUE THREAD

**Issue by MonicaLiu0311** [eProsima/Fast-DDS#3451]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

No error.

### Current behavior

Hello, I'm a member of Microsoft [VCPKG](https://github.com/microsoft/vcpkg), when I built this port in an internal version of MSVC, it failed with following errors:
```
D:\buildtrees\fastrtps\src\v2.7.0-5b113921c9.clean\include\fastrtps/utils/TimedMutex.hpp(93): error C2065: 'xtime': undeclared identifier
D:\buildtrees\fastrtps\src\v2.7.0-5b113921c9.clean\include\fastrtps/utils/TimedMutex.hpp(93): error C2059: syntax error: ')'
```

### Steps to reproduce

Build with MSVC `19.36.32528.95` and above, `xtime` has been changed to `_timespec64` since https://github.com/microsoft/STL/pull/3594, it's an upcoming release.

### Fast DDS version/commit

`2.7.0`. For details, see: [fastrtps/vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/ports/fastrtps/vcpkg.json)

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

* Windows
* Visual Studio

**Comment by MiguelCompany** [comment]
@MonicaLiu0311 I am thinking of adding this to the beginning of the `TimedMutex` class:

```
#if defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 193632528
    using xtime = _timespec64;
#endif  // _MSC_FULL_VER check
```

Do you think it would be enough?

**Comment by MonicaLiu0311** [comment]
> @MonicaLiu0311 I am thinking of adding this to the beginning of the TimedMutex class:
> ```
> #if defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 193632528
>     using xtime = _timespec64;
> #endif  // _MSC_FULL_VER check
> ```
> Do you think it would be enough?


I did the actual verification and your change passed in MSVC internal tests.

**Comment by MiguelCompany** [comment]
@MonicaLiu0311 Thanks for your confirmation. I created #3462 with the fix, which will be backported to the currently supported versions (2.10.x, 2.9.x, 2.6.x, and 2.1.x)
