### ISSUE TITLE
Build error because of -Werror=template-id-cdtor in C++20

### ISSUE THREAD

**Issue by kistlin** [eProsima/Fast-DDS#5340]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Build completes without errors.

### Current behavior

Build breaks with `thirdparty/filewatch/FileWatch.hpp:129:22: error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]`.

### Steps to reproduce

Build with gcc (GCC) 14.2.1 20240910.

### Fast DDS version/commit

3.1.0 and later for sure.

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM
